version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: netgenius-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d netgenius" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - netgenius-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netgenius-app
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - netgenius-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  netgenius-network:
    driver: bridge