spring.application.name=net-genius

spring.datasource.url=jdbc:postgresql://localhost:5432/netgenius
spring.datasource.username=postgres
spring.datasource.password=sunrise

testing.app.secret=c40e168dc7657265c97a10390454a871
testing.app.lifetime=600000
jwt.secret=S3cr3tK3yForJWTAuthN3tG3niu5B4ck3nDPr0j3ct!@#$

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

logging.level.org.springframework.security=TRACE
