spring.application.name=net-genius

spring.datasource.url=jdbc:postgresql://localhost:5432/netgenius
spring.datasource.username=postgres
spring.datasource.password=Egor1199

testing.app.secret=c40e168dc7657265c97a10390454a871
testing.app.lifetime=600000

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# Настройки логирования
logging.level.root=INFO
logging.level.com.simul_tech.netgenius=DEBUG
logging.file.name=logs/netgenius.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.org.springframework.security=TRACE
