spring.application.name=net-genius

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=89017512504

testing.app.secret=c40e168dc7657265c97a10390454a871
testing.app.lifetime=600000

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
server.port=8081

logging.level.org.springframework.security=TRACE
